global:
  address: 0.0.0.0:8080
  port: 8080
  logfile: /dev/stderr
logging:
  level: debug
storage:
  cleanup-period: 5sm
  syncpool: 5
  maxmessagesize: 0
  chunksize: 1024
  writeconcern: 1
  allowtopicscreation: true
# driver:
#   inmemory: {}
  driver:
    goleveldb:
      rootdir: /tmp/storage
etcd:
  no-server: false
  storage-dir: "/tmp/etcd"
  name: default
  initial-cluster: default=http://0.0.0.0:2380
  initial-cluster-state: new

  client:
    urls:
      - http://0.0.0.0:2379

    # Path to the client server TLS cert file.
    cert-file:

    # Path to the client server TLS key file.
    key-file:

    # Enable client cert authentication.
    client-cert-auth: false

    # Path to the client server TLS trusted CA key file.
    trusted-ca-file:

    # Client TLS using generated certificates
    auto-tls: false
  peer:
    urls:
      - http://0.0.0.0:2380

    # Path to the peer server TLS cert file.
    cert-file:

    # Path to the peer server TLS key file.
    key-file:

    # Enable peer client cert authentication.
    client-cert-auth: false

    # Path to the peer server TLS trusted CA key file.
    trusted-ca-file:

    # Peer TLS using generated certificates.
    auto-tls: false

  advertise-client:
    urls:
      - http://0.0.0.0:2379
  advertise-peer:
    urls:
      - http://0.0.0.0:2380
  discovery-proxy:
  discovery-srv:
  discovery:
